version: "3.7"

services:

  nginx:
    build: ./nginx
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ..:/app

  pgsql:
    build: ./pgsql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgsql/.data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  php:
    build: ./php
    working_dir: /app
    ports:
      - 9000:9000
    volumes:
      - ..:/app